import "./globals.css";
import "@radix-ui/themes/styles.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cultivate Prototyping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className="">{children}</body>
    </html>
  );
}
